### ISSUE TITLE
Add a calendar widget to filter data

### ISSUE THREAD

**Issue by dsully-dev** [creare-com/podpac-drought-monitor#11]
@mpu-creare Do you have specifications in mind already, or would you like me to come up with them? I just cloned and served the drought monitor, and can poke around for good existing calendar widgets. I'll also need to familiarize myself with the code a bit to understand how data is queries and where the date/time is used.

**Comment by dsully-dev** [comment]
I can't assign myself to this for some reason, but will start working this.

**Comment by mpu-creare** [comment]
I dont have a spec in mind. The WG calendar is pretty a good example. We don't need to limit unavailable dates, and we don't need the hour resolution (only daily).

**Comment by mpu-creare** [comment]
Thanks!

**Comment by dsully-dev** [comment]
Here is a first pass at adding a date range picker. This seems an appropriate widget to use based on its level of flexibility and simplicity. I think it makes sense to put it in the top bar, since our lat/lon controls are there.

![image](https://user-images.githubusercontent.com/20960952/76228516-36a7bb80-61f7-11ea-92ad-f3e6fcebd76d.png)

**Comment by mpu-creare** [comment]
http://ndmc-001.unl.edu:8080/cgi-bin/mapserv.exe?map=/ms4w/apps/usdm/service/usdm_20200303_wms.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=usdm20200303&WIDTH=640&HEIGHT=480&crs=EPSG:3857&styles=default&format=image/png&bbox=-18367715.9809,1689200.13961,-6679169.4476,15538711.0963

This is the format for the WMS feed from the NDMC (note the date shows up both in the URL and then layer name) -- unfortunately, not all dates have data, so we'll have to do a get-capabilities call -- makes it a little more complicated.

**Comment by mpu-creare** [comment]
Actually, looks like they can't do a getcapabilities call, so we can hack it by just calling into the API and then looking at the dates that come back... then selecting the closest one.

**Comment by dsully-dev** [comment]
@mpu-creare Note I started this with 91bb7d8013d281c77afa660575fb923ed9f13bf0 and 6df32361ef8fafc39f69f9b9f43c090ad26b4602

I'm hoping you can show me where the layers actually request data, since I'll need to invoke that on each calendar widget selection. You'll see that I moved `L.tilelayer.wms` creation for the layers that use a date into a function, which is called when the user selects a date.

**Comment by mpu-creare** [comment]
I did a little bit of googling and came across this: https://gis.stackexchange.com/questions/270445/redraw-refresh-wms-layer-in-leaflet 

Does that help? Is that what you are asking? I don't actually make the layers request data anywhere in my code -- that happens internal to leaflet.

**Comment by dsully-dev** [comment]
@mpu-creare I believe this is working for SMAP VSM/DMI layers. I haven't added the NDMI layer yet, but will do so shortly. However, I'm only able to retrieve data for the current date or last few days. When I select any other date, the requests are made, but Lambda function returns 502. I'm guessing this has to do with data staging being done on AWS and/or the Lambda node? At any rate, I believe the client is correctly re-requesting WMS layers with updated date selections.
