### ISSUE TITLE
Legend Updates

### ISSUE THREAD

**Issue by mpu-creare** [creare-com/podpac-drought-monitor#13]
* Add the explicit date for NDMI and SMAP in the legend. 
* Make the legend specific to the display (i.e. remove the line decorators in the current map view).

**Comment by dsully-dev** [comment]
Note: these will be `queryDate` for SMAP data layers, and `ndmiDate` for NDMI data (both in `app.js`).

**Comment by dsully-dev** [comment]
I don't believe I did this yet, which might have been why I left the merge request open before. At any rate, I'll try to do this tomorrow and use a new MR.
